config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/john-shepherdson/eosc.service-cat-api.adapter:
      branch: main
      repo: https://github.com/john-shepherdson/eosc.service-cat-api.adapter.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter git:
        commands:
        - /usr/bin/env sh .sqa/script.mist_articulate_rabbit.sh
        container: qc.acc_malachite_amiable_quail
  QC.Doc:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.eggplant_outgoing_hornbill.sh
        container: qc.doc_plum_reckless_meerkat
      github.com/john-shepherdson/eosc.service-cat-api.adapter git:
        commands:
        - /usr/bin/env sh .sqa/script.purple_clever_bullfrog.sh
        container: qc.doc_lavender_amiable_sloth
      github.com/john-shepherdson/eosc.service-cat-api.adapter markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.horizon_cheerful_kingfisher.sh
        container: qc.doc_orchid_nurturing_osprey
  QC.Lic:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sapphire_devoted_kookaburra.sh
        container: qc.lic_cyan_hopeful_barracuda
  QC.Met:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.mulberry_smart_gnu.sh
        container: qc.met_green_fair_penguin
  QC.Sty:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.seafoam_elated_uakari.sh
        container: qc.sty_pink_brilliant_wolverine
      github.com/john-shepherdson/eosc.service-cat-api.adapter jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ebony_mature_reindeer.sh
        container: qc.sty_mustard_serene_groundhog
  QC.Ver:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunset_scrappy_kiwi.sh
        container: qc.ver_beige_spirited_ferret
timeout: 5400
