config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/john-shepherdson/eosc.service-cat-api.adapter:
      branch: main
      repo: https://github.com/john-shepherdson/eosc.service-cat-api.adapter.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter git:
        commands:
        - /usr/bin/env sh .sqa/script.arctic_aware_seal.sh
        container: qc.acc_incarnadine_practical_alligator
  QC.Doc:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.vermilion_intuitive_cobra.sh
        container: qc.doc_caramel_dramatic_tiger
      github.com/john-shepherdson/eosc.service-cat-api.adapter git:
        commands:
        - /usr/bin/env sh .sqa/script.navy_zealous_sparrow.sh
        container: qc.doc_lavender_innocent_gibbon
      github.com/john-shepherdson/eosc.service-cat-api.adapter markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cinnamon_ardent_dragonfly.sh
        container: qc.doc_jasmine_tactful_orca
  QC.Lic:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter licensee:
        commands:
        - /usr/bin/env sh .sqa/script.vermilion_adventurous_antelope.sh
        container: qc.lic_ivory_proactive_salamander
  QC.Met:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.carmine_audacious_pangolin.sh
        container: qc.met_byzantium_devoted_badger
  QC.Sty:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.violet_innocent_cobra.sh
        container: qc.sty_fern_loyal_eagle
      github.com/john-shepherdson/eosc.service-cat-api.adapter jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.banana_foolish_leopard.sh
        container: qc.sty_jade_inspired_wolverine
  QC.Ver:
    repos:
      github.com/john-shepherdson/eosc.service-cat-api.adapter get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cerulean_determined_quail.sh
        container: qc.ver_gamboge_zealous_hydra
timeout: 5400
